services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"

  test:
    build: .
    command: npm test
    depends_on:
      - mongo
    environment:
      NODE_ENV: test
      DEVKIT_NODE_db_uri: mongodb://mongo:27017/NodeTest
