version: '3'

services:
  node:
    container_name: node
    image: pierreb/node:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - node:/data
    networks:
      - mongo
    depends_on:
      - mongo
    environment:
      - 'DEVKIT_NODE_db_uri=mongodb://mongo:27017/NodeDev'
      - 'DEVKIT_NODE_host=0.0.0.0'

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data
    networks:
      - mongo

networks:
  mongo:
    driver: bridge

volumes:
  node:
  mongo:
